version: "3.8"
services:
  web:
    container_name: flask-app
    build: .
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/code
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    #   MYSQL_DATABASE: MY_DATABASE
    #   MYSQL_USER: MYSQL_USER
    #   MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    container_name: phpma
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    restart: always
    environment:
      PMA_HOST: db
volumes:
  dbdata:
